/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRdxImageRouteImport } from './routes/api/rdx-image'
import { Route as ApiRdxVideoRouteImport } from './routes/api/rdx-video'
import { Route as ApiRdxVoiceRouteImport } from './routes/api/rdx-voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdxImageRoute = ApiRdxImageRouteImport.update({
  id: '/api/rdx-image',
  path: '/api/rdx-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdxVideoRoute = ApiRdxVideoRouteImport.update({
  id: '/api/rdx-video',
  path: '/api/rdx-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdxVoiceRoute = ApiRdxVoiceRouteImport.update({
  id: '/api/rdx-voice',
  path: '/api/rdx-voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/rdx-image': typeof ApiRdxImageRoute
  '/api/rdx-video': typeof ApiRdxVideoRoute
  '/api/rdx-voice': typeof ApiRdxVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/rdx-image': typeof ApiRdxImageRoute
  '/api/rdx-video': typeof ApiRdxVideoRoute
  '/api/rdx-voice': typeof ApiRdxVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/rdx-image': typeof ApiRdxImageRoute
  '/api/rdx-video': typeof ApiRdxVideoRoute
  '/api/rdx-voice': typeof ApiRdxVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/rdx-image' | '/api/rdx-video' | '/api/rdx-voice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/rdx-image' | '/api/rdx-video' | '/api/rdx-voice'
  id: '__root__' | '/' | '/api/rdx-image' | '/api/rdx-video' | '/api/rdx-voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRdxImageRoute: typeof ApiRdxImageRoute
  ApiRdxVideoRoute: typeof ApiRdxVideoRoute
  ApiRdxVoiceRoute: typeof ApiRdxVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdx-image': {
      id: '/api/rdx-image'
      path: '/api/rdx-image'
      fullPath: '/api/rdx-image'
      preLoaderRoute: typeof ApiRdxImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdx-video': {
      id: '/api/rdx-video'
      path: '/api/rdx-video'
      fullPath: '/api/rdx-video'
      preLoaderRoute: typeof ApiRdxVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdx-voice': {
      id: '/api/rdx-voice'
      path: '/api/rdx-voice'
      fullPath: '/api/rdx-voice'
      preLoaderRoute: typeof ApiRdxVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRdxImageRoute: ApiRdxImageRoute,
  ApiRdxVideoRoute: ApiRdxVideoRoute,
  ApiRdxVoiceRoute: ApiRdxVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
